import 'dart:collection';

/// Queue used to handle voice prompts generated by different parts of the
/// application. The queue is typed loosely to match the behaviour of the
/// original Python implementation.
class VoicePromptQueue {
  final Queue<String> _arQueue = Queue<String>();

  /// Removes all queued augmented reality prompts for the provided [voice].
  void clearArqueue(dynamic voice) {
    _arQueue.clear();
  }

  /// Adds an augmented reality status update for the provided [voice].
  void produceArStatus(dynamic voice, String status) {
    _arQueue.add(status);
  }

  /// Retrieves the next AR status if available.
  String? consumeArStatus() {
    return _arQueue.isNotEmpty ? _arQueue.removeFirst() : null;
  }
}

